---
- name: Install ping-pong service
  hosts: localhost
  become: true
  vars:
    jenkins_http_port: 8081
    jenkins_process_user: jenkins
    jenkins_plugins: 
      - blueocean
      - git
      - http_request
    docker_users:
      - jenkins

  tasks:
    - name: Install tools
      include_role: 
        name: prereq
        apply:
          tags: prereq
      tags: prereq
    
    - name: Install Jenkins
      include_role: 
        name: geerlingguy.jenkins
        apply:
          tags: jenkins
      tags: jenkins
    
    - name: Install Docker
      include_role: 
        name: geerlingguy.docker
        apply:
          tags: docker
      tags: docker

    - name: restart jenkins
      service: name=jenkins state=restarted
      tags: restart_svc

    - name: restart docker
      service: name=docker state=restarted
      tags: restart_svc

    - name: Import job
      shell: "java -jar /opt/jenkins-cli.jar -s http://localhost:{{jenkins_http_port}} -auth admin:admin create-job test_task < test_task.xml"
      tags: test_task



    
