---
- name: Install ping-pong service
  hosts: localhost
  become: true
  vars:
    jenkins_http_port: 8081
    jenkins_process_user: jenkins
    jenkins_plugins: 
      - blueocean
      - git
      - http_request
    docker_users:
      - jenkins

  tasks:
    - name: Install tools
      include_role: 
        name: prereq
        apply:
          tags: prereq
      tags: prereq
    
    - name: Install Jenkins
      include_role: 
        name: geerlingguy.jenkins
        apply:
          tags: jenkins
      tags: jenkins
    
    - name: Install Docker
      include_role: 
        name: geerlingguy.docker
        apply:
          tags: docker
      tags: docker

    - name: restart jenkins
      service: name=jenkins state=restarted
      tags: restart_svc

    - name: restart docker
      service: name=docker state=restarted
      tags: restart_svc

    - name: Wait for Jenkins to start up before proceeding.
      uri:
        url: "http://localhost:{{ jenkins_http_port }}/cli/"
        method: GET
        return_content: "yes"
        timeout: 5
        body_format: raw
        follow_redirects: "no"
        status_code: 200,403
      register: result
      until: (result.status == 403 or result.status == 200) and (result.content.find("Please wait while") == -1)
      retries: 10
      delay: 5
      changed_when: false
      check_mode: false
      tags: wait

    - name: Import job
      shell: "java -jar /opt/jenkins-cli.jar -s http://localhost:{{jenkins_http_port}} -auth admin:admin create-job test_task < test_task.xml"
      tags: test_task



    
